apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/ahmetcanyilmaz2022/taskmanager-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-db
      imagePullSecrets:
        - name: ghcr-secret
