apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  DATABASE_URL: cG9zdGdyZXM6cG9zdGdyZXNAMS1zcGVuZC1wb3N0Z3JlczoyNTQzL3Rhc2tkYg==
